services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ai-health-log_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=ai-health-log
      - SPRING_DATASOURCE_PASSWORD=ai-health-log
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ai-health-log_db
      - MYSQL_USER=ai-health-log
      - MYSQL_PASSWORD=ai-health-log
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
